sudo: required
services: 
    - docker
before-install:
    - docker build -t mmo/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run mmo/react-test npm test -- --coverage

after_success:
    - docker build -t mmo/multi-client ./client
    - docker build -t mmo/multi-server ./server
    - docker build -t mmo/multi-nginx ./nginx
    - docker build -t mmo/multi-worker ./worker

    #login 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #push
    - docker push mmo/multi-client
    - docker push mmo/multi-server
    - docker push mmo/multi-nginx
    - docker push mmo/multi-worker

